### ISSUE TITLE
Missing required PIL module

### ISSUE THREAD

**Issue by laszukdawid** [PettingZoo-Team/PettingZoo#446]
## Issue

It seems that default import `import pettingzoo` depends on PIL package but it isn't specified in required dependencies.

## Reproduce

```bash
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install -q pettingzoo  # Error: Failed building wheel for pettingzoo
$ python -c "import pettingzoo"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kretyn/tmp/.venv/lib/python3.8/site-packages/pettingzoo/__init__.py", line 1, in <module>
    from pettingzoo.utils import AECEnv, ParallelEnv
  File "/home/kretyn/tmp/.venv/lib/python3.8/site-packages/pettingzoo/utils/__init__.py", line 5, in <module>
    from .save_observation import save_observation
  File "/home/kretyn/tmp/.venv/lib/python3.8/site-packages/pettingzoo/utils/save_observation.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by jkterry1** [comment]
I just fixed this on master, thanks a ton!

**Comment by laszukdawid** [comment]
Hey @jkterry1, sorry got confused by this. What do you mean by this being fixed on master?
I can see that the [culprit is still there](https://github.com/PettingZoo-Team/PettingZoo/blob/11c6c9bf25d900077dcb3d578db50e93bcc933e6/pettingzoo/utils/save_observation.py#L5) and that freshly downloading package from pip still fails.

**Comment by benblack769** [comment]
@jkterry1 Yeah, given the import structure here, it needs to be a base requirement, or else it just breaks everything. Perhaps your intention was to make it an optional `other` requirement? If so, then probably the import should go within the `save_observtion` function.

```
def save_observation(env, agent=None, all_agents=False, save_dir=os.getcwd()):
      from PIL import Image
```

**Comment by jkterry1** [comment]
Closed by the PR I just merged
